### ISSUE TITLE
Send to output

### ISSUE THREAD

**Issue by espenbo** [hansrune/HANmeter#2]
Hello
I could not get the script to send output to a text file
python3 HANdomo.py -f /dev/ttyUSB0 > test.txt

If you add in the script 'sys.stdout.flush()' it works.

---------- Orginal ----------------
```
def gen_callback(fields):
    global npower, sumpower, lastupdatetime, nenergy, sumenergy
    if logdata:
        outputFile.flush()
    if debugfields:
        for key in sorted(fields.keys()):
            print(key,"=",fields[key])
        print("")
    if poweridx == 0:
```

----------- Endret ------------
```
def gen_callback(fields):
    global npower, sumpower, lastupdatetime, nenergy, sumenergy
    if logdata:
        outputFile.flush()
    if debugfields:
        for key in sorted(fields.keys()):
            print(key,"=",fields[key])
        print("")
        sys.stdout.flush()
    if poweridx == 0:
```

Then it works to use
python3 HANdomo.py -f /dev/ttyUSB0 > test.txt``

**Comment by hansrune** [comment]
I added the flush after the callback has been called in HANobis.py so that output is flushed no matter what the callback is doing. You should then be able to output to a file or pipe without buffering delays. 

When run as a service, it is always unbuffered as python3 is started in unbuffered (-u) mode
